<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE SyslogEvent PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<SyslogEvent classname="sailpoint.api.SailPointFactory" eventLevel="ERROR" lineNumber="402" quickKey="0000000963" server="LAPTOP-9SCDGNAQ" thread="ServerThread" username="Services">
  <EventMessage>Could not close context: Unable to rollback against JDBC Connection</EventMessage>
  <Stacktrace>sailpoint.tools.GeneralException: Unable to rollback against JDBC Connection
	at sailpoint.persistence.HibernatePersistenceManager.close(HibernatePersistenceManager.java:638)
	at sailpoint.persistence.ClassPersistenceManager.close(ClassPersistenceManager.java:228)
	at sailpoint.server.InternalContext.close(InternalContext.java:565)
	at sailpoint.api.SailPointFactory.releaseContext(SailPointFactory.java:399)
	at sailpoint.api.SailPointFactory.releaseContext(SailPointFactory.java:418)
	at sailpoint.server.Servicer.processServices(Servicer.java:950)
	at sailpoint.server.Servicer.run(Servicer.java:677)
Caused by: org.hibernate.TransactionException: Unable to rollback against JDBC Connection
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:127)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.rollback(JdbcResourceLocalTransactionCoordinatorImpl.java:304)
	at org.hibernate.engine.transaction.internal.TransactionImpl.rollback(TransactionImpl.java:142)
	at sailpoint.persistence.HibernatePersistenceManager.close(HibernatePersistenceManager.java:628)
	... 6 more
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1865)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:484)
	at org.apache.commons.dbcp2.DelegatingConnection.rollback(DelegatingConnection.java:484)
	at sailpoint.persistence.ConnectionWrapper.rollback(ConnectionWrapper.java:191)
	at org.hibernate.resource.jdbc.internal.AbstractLogicalConnectionImplementor.rollback(AbstractLogicalConnectionImplementor.java:121)
	... 9 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at jdk.internal.reflect.GeneratedConstructorAccessor159.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:576)
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1819)
	... 13 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 1,570,663 milliseconds ago. The last packet sent successfully to the server was 1,570,664 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:575)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:630)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2304)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2057)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2019)
	at org.hibernate.loader.hql.QueryLoader.iterate(QueryLoader.java:530)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.iterate(QueryTranslatorImpl.java:441)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performIterate(HQLQueryPlan.java:320)
	at org.hibernate.internal.SessionImpl.iterate(SessionImpl.java:1534)
	at org.hibernate.query.internal.AbstractProducedQuery.doIterate(AbstractProducedQuery.java:1533)
	at org.hibernate.query.internal.AbstractProducedQuery.iterate(AbstractProducedQuery.java:1521)
	at sailpoint.persistence.HibernatePersistenceManager.search(HibernatePersistenceManager.java:2100)
	at sailpoint.persistence.ClassPersistenceManager.search(ClassPersistenceManager.java:334)
	at sailpoint.server.InternalContext.search(InternalContext.java:893)
	at sailpoint.web.Authorizer.getModificationDate(Authorizer.java:184)
	at sailpoint.web.Authorizer.checkRefresh(Authorizer.java:159)
	at sailpoint.server.CacheService.execute(CacheService.java:244)
	at sailpoint.server.Servicer.execute(Servicer.java:982)
	at sailpoint.server.Servicer.processServices(Servicer.java:933)
	... 1 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:566)
	... 26 more
</Stacktrace>
</SyslogEvent>