<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE SyslogEvent PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<SyslogEvent classname="sailpoint.persistence.HibernatePersistenceManager" eventLevel="ERROR" lineNumber="465" quickKey="0000002107" server="LAPTOP-9SCDGNAQ" thread="ServerThread" username="Services">
  <EventMessage>Unable to check isolation level</EventMessage>
  <Stacktrace>java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.versionMeetsMinimum(ConnectionImpl.java:2327)
	at com.mysql.cj.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:1219)
	at org.apache.commons.dbcp2.DelegatingConnection.getTransactionIsolation(DelegatingConnection.java:425)
	at org.apache.commons.dbcp2.DelegatingConnection.getTransactionIsolation(DelegatingConnection.java:425)
	at sailpoint.persistence.ConnectionWrapper.getTransactionIsolation(ConnectionWrapper.java:123)
	at sailpoint.persistence.HibernatePersistenceManager.getSession(HibernatePersistenceManager.java:455)
	at sailpoint.persistence.HibernatePersistenceManager.search(HibernatePersistenceManager.java:2083)
	at sailpoint.persistence.ClassPersistenceManager.search(ClassPersistenceManager.java:334)
	at sailpoint.server.InternalContext.search(InternalContext.java:893)
	at sailpoint.server.Servicer.getModificationDate(Servicer.java:1099)
	at sailpoint.server.CacheService.refresh(CacheService.java:377)
	at sailpoint.server.CacheService.refresh(CacheService.java:319)
	at sailpoint.server.CacheService.refresh(CacheService.java:260)
	at sailpoint.server.CacheService.execute(CacheService.java:226)
	at sailpoint.server.Servicer.execute(Servicer.java:982)
	at sailpoint.server.Servicer.processServices(Servicer.java:933)
	at sailpoint.server.Servicer.run(Servicer.java:677)
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:576)
	at com.mysql.cj.jdbc.ConnectionImpl.versionMeetsMinimum(ConnectionImpl.java)
	... 16 more
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet successfully received from the server was 124,291 milliseconds ago. The last packet sent successfully to the server was 124,291 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:575)
	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:630)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:946)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:122)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2304)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2057)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2019)
	at org.hibernate.loader.hql.QueryLoader.iterate(QueryLoader.java:530)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.iterate(QueryTranslatorImpl.java:441)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performIterate(HQLQueryPlan.java:320)
	at org.hibernate.internal.SessionImpl.iterate(SessionImpl.java:1534)
	at org.hibernate.query.internal.AbstractProducedQuery.doIterate(AbstractProducedQuery.java:1533)
	at org.hibernate.query.internal.AbstractProducedQuery.iterate(AbstractProducedQuery.java:1521)
	at sailpoint.persistence.HibernatePersistenceManager.search(HibernatePersistenceManager.java:2100)
	at sailpoint.persistence.ClassPersistenceManager.search(ClassPersistenceManager.java:334)
	at sailpoint.server.InternalContext.search(InternalContext.java:893)
	at sailpoint.server.HeartbeatService.getLateServers(HeartbeatService.java:338)
	at sailpoint.server.HeartbeatService.housekeeping(HeartbeatService.java:304)
	at sailpoint.server.HeartbeatService.execute(HeartbeatService.java:223)
	at sailpoint.server.Servicer.execute(Servicer.java:982)
	at sailpoint.server.Servicer.processServices(Servicer.java:924)
	... 1 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
	at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
	at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:566)
	... 26 more
</Stacktrace>
</SyslogEvent>